<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKY6xhuo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKY6xhuo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKY6xhuo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKY6xhuo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKY6xhuo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KY6xhuo',
    'container.build_id' => '9e3fdc43',
    'container.build_time' => 1555318071,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKY6xhuo');
