<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTx1UJ9K\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTx1UJ9K/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTx1UJ9K.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTx1UJ9K\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTx1UJ9K\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Tx1UJ9K',
    'container.build_id' => '5a59b12a',
    'container.build_time' => 1555423544,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTx1UJ9K');
