<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLyAxAeB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLyAxAeB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLyAxAeB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLyAxAeB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLyAxAeB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LyAxAeB',
    'container.build_id' => 'bb3a75c9',
    'container.build_time' => 1555506482,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLyAxAeB');
