<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYOlTgNA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYOlTgNA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYOlTgNA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYOlTgNA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYOlTgNA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YOlTgNA',
    'container.build_id' => 'f63d583d',
    'container.build_time' => 1555427393,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYOlTgNA');
